/* ==========================================================================
   Racing Hobbies Ecuador — Catálogo de productos
   Inventario real de la tienda (racinghobbiesec.com). Precios en USD.
   `img` apunta a assets/img/. Editar aquí actualiza todo el sitio.
   ========================================================================== */

const RH_CATEGORIES = Object.freeze([
  { slug: "crawlers", label: "Crawlers 4x4" },
  { slug: "pista", label: "Autos de Pista" },
  { slug: "monster", label: "Monster y Off-Road" },
  { slug: "camiones", label: "Camiones y Trailers" },
  { slug: "aviones", label: "Aviones RC" },
  { slug: "helis", label: "Helicópteros" },
  { slug: "energia", label: "Baterías" },
  { slug: "nitro", label: "Nitro y Repuestos" },
]);

const RH_PRODUCTS = Object.freeze([
  /* ---------- Crawlers 4x4 ---------- */
  {
    id: "camel-defender",
    name: "Land Rover Camel Trophy Defender 1/10",
    cat: "crawlers",
    price: 710,
    tag: "top",
    img: "assets/img/camel-defender.webp",
    desc: "El icónico Defender de las expediciones Camel Trophy en escala 1/10: tracción 4x4, detalle extremo y capacidad real para superar cualquier terreno.",
    specs: ["Escala 1/10, 4x4", "Edición Camel Trophy", "Listo para correr (RTR)", "Detalle de expedición realista"],
  },
  {
    id: "camel-discovery",
    name: "Land Rover Camel Trophy Discovery 1/10",
    cat: "crawlers",
    price: 710,
    tag: null,
    img: "assets/img/camel-discovery.webp",
    desc: "Crawler de estilo clásico con tracción 4x4, detalles fieles al Discovery original y desempeño sobresaliente en rutas difíciles.",
    specs: ["Escala 1/10, 4x4", "Edición Camel Trophy", "Listo para correr (RTR)", "Carrocería de alto detalle"],
  },
  {
    id: "toyota-land-cruiser",
    name: "FMS Toyota Land Cruiser 1/10",
    cat: "crawlers",
    price: 650,
    tag: null,
    img: "assets/img/toyota-land-cruiser.webp",
    desc: "Crawler altamente detallado con tracción 4x4, acabado realista y excelente rendimiento off-road.",
    specs: ["Escala 1/10, 4x4", "Acabado premium FMS", "Listo para correr (RTR)", "Excelente en terreno difícil"],
  },
  {
    id: "toyota-fj40",
    name: "FMS Toyota FJ40 1/10",
    cat: "crawlers",
    price: 650,
    tag: "top",
    img: "assets/img/toyota-fj40.webp",
    desc: "Un clásico legendario hecho crawler: servo en el volante, sistema completo de luces y detalle de museo.",
    specs: ["Escala 1/10, 4x4", "Sistema de luces completo", "Servo en el volante", "Diseño icónico FJ40"],
  },
  {
    id: "everest-ascent",
    name: "Redcat Everest Ascent 1/10",
    cat: "crawlers",
    price: 580,
    tag: null,
    img: "assets/img/everest-ascent.webp",
    desc: "Todoterreno de alto rendimiento con chasis resistente, tracción 4x4 y gran capacidad de ascenso en terrenos extremos.",
    specs: ["Escala 1/10, 4x4", "Chasis de alto rendimiento", "Gran ángulo de ascenso", "Listo para correr (RTR)"],
  },
  {
    id: "everest-gen7",
    name: "Redcat Everest Gen7 Sport 1/10",
    cat: "crawlers",
    price: 425,
    tag: null,
    img: "assets/img/everest-gen7.webp",
    desc: "Crawler eléctrico con chasis de acero, suspensión de 4 brazos y gran ángulo de articulación para lo más extremo.",
    specs: ["Escala 1/10, 4x4", "Chasis de acero", "Suspensión de 4 brazos", "Listo para correr (RTR)"],
  },
  {
    id: "landrover-series2",
    name: "FMS Land Rover Series II 1/12",
    cat: "crawlers",
    price: 350,
    tag: null,
    img: "assets/img/landrover-series2.webp",
    desc: "Crawler 1/12 detallado con tracción 4x4: potente y portátil para jugarlo dentro y fuera de casa.",
    specs: ["Escala 1/12, 4x4", "Compacto y portátil", "Alto detalle FMS", "Interior y exterior"],
  },
  {
    id: "k5-blazer",
    name: "FMS Chevrolet K5 Blazer 1/24",
    cat: "crawlers",
    price: 250,
    tag: "nuevo",
    img: "assets/img/k5-blazer.webp",
    desc: "Crawler 2 en 1 con tracción 4x4: conviértelo de camioneta a blazer cuando quieras.",
    specs: ["Escala 1/24, 4x4", "Convertible 2 en 1", "Alto detalle", "Ideal para interiores"],
  },
  {
    id: "lc80-v2",
    name: "FMS Toyota LC80 V2 1/18",
    cat: "crawlers",
    price: 265,
    tag: null,
    img: "assets/img/lc80-v2.webp",
    desc: "Crawler altamente detallado con tracción 4x4, ejes metálicos y sistema de luces.",
    specs: ["Escala 1/18, 4x4", "Ejes metálicos", "Sistema de luces", "Listo para correr (RTR)"],
  },
  {
    id: "defender-124",
    name: "FMS Land Rover Defender 1/24",
    cat: "crawlers",
    price: 230,
    tag: null,
    img: "assets/img/defender-124.webp",
    desc: "El Defender en formato bolsillo: tracción 4x4, acabado realista y gran desempeño en miniatura.",
    specs: ["Escala 1/24, 4x4", "Alto detalle", "Portátil", "Listo para correr (RTR)"],
  },
  {
    id: "discovery-124",
    name: "FMS Land Rover Discovery 1/24",
    cat: "crawlers",
    price: 230,
    tag: null,
    img: "assets/img/discovery-124.webp",
    desc: "Crawler compacto con tracción 4x4 y acabado realista, listo para la aventura en cualquier lugar.",
    specs: ["Escala 1/24, 4x4", "Alto detalle", "Portátil", "Listo para correr (RTR)"],
  },
  {
    id: "redcat-ascent-118",
    name: "Redcat Ascent 1/18",
    cat: "crawlers",
    price: 220,
    tag: null,
    img: "assets/img/redcat-ascent-118.webp",
    desc: "Crawler escala 1/18 con tracción total 4x4: potente y portátil para jugarlo dentro y fuera de casa.",
    specs: ["Escala 1/18, 4x4", "Tracción total", "Compacto", "Listo para correr (RTR)"],
  },
  {
    id: "wendigo",
    name: "Redcat Wendigo Builders Kit",
    cat: "crawlers",
    price: 425,
    tag: null,
    img: "assets/img/wendigo.webp",
    desc: "Kit de montaje tipo rock racer: chasis metálico, suspensión ajustable y transmisión 4WD. Para armadores de verdad.",
    specs: ["Kit de ensamblaje", "Chasis metálico", "Suspensión ajustable", "Requiere electrónica y motor"],
  },

  /* ---------- Autos de Pista (Tamiya TT-02) ---------- */
  {
    id: "lancia-delta",
    name: "Tamiya Lancia Delta Integrale TT-02",
    cat: "pista",
    price: 300,
    tag: "top",
    img: "assets/img/lancia-delta.webp",
    desc: "Leyenda del rally sobre chasis TT-02 4WD: suspensión independiente, diferenciales y carrocería de alta precisión.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Diferencial delantero/trasero", "Carrocería de alta precisión"],
  },
  {
    id: "golf-gti",
    name: "Tamiya VW Golf II GTI 16V Rally",
    cat: "pista",
    price: 311,
    tag: null,
    img: "assets/img/golf-gti.webp",
    desc: "El Golf II GTI de rally sobre TT-02 4WD: rendimiento preciso y estable en pistas RC.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Carrocería GTI 16V Rally", "Preciso y estable"],
  },
  {
    id: "mercedes-190e",
    name: "Tamiya Mercedes-Benz 190E EVO II",
    cat: "pista",
    price: 300,
    tag: null,
    img: "assets/img/mercedes-190e.webp",
    desc: "La bestia del DTM sobre chasis TT-02 4WD con geometría optimizada para pista.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Geometría optimizada", "Carrocería EVO II"],
  },
  {
    id: "subaru-impreza",
    name: "Tamiya Subaru Impreza Monte-Carlo '99",
    cat: "pista",
    price: 300,
    tag: null,
    img: "assets/img/subaru-impreza.webp",
    desc: "El Impreza del Monte-Carlo '99: chasis TT-02 4WD con ajustes de altura y distancia entre ejes, para asfalto y tierra.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Ajuste de altura", "Distancia entre ejes ajustable", "Asfalto y tierra"],
  },
  {
    id: "mercedes-c11",
    name: "Tamiya Mercedes-Benz C11 1990",
    cat: "pista",
    price: 280,
    tag: null,
    img: "assets/img/mercedes-c11.webp",
    desc: "Prototipo de resistencia con chasis rígido de composite, bañera de resina ABS y suspensión independiente.",
    specs: ["Escala 1/10", "Chasis composite rígido", "Suspensión independiente", "Carrocería detallada"],
  },
  {
    id: "toyota-toms",
    name: "Tamiya Toyota Tom's 84C",
    cat: "pista",
    price: 225,
    tag: null,
    img: "assets/img/toyota-toms.webp",
    desc: "Fiel al prototipo de resistencia de 1984, sobre chasis TT-02 4WD con suspensión independiente.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Réplica del 84C de 1984", "Para pista"],
  },

  /* ---------- Monster y Off-Road ---------- */
  {
    id: "tmaxx",
    name: "Traxxas T-Maxx Nitro 4WD",
    cat: "monster",
    price: 800,
    tag: "top",
    img: "assets/img/tmaxx.webp",
    desc: "El rey del nitro: arranque eléctrico EZ-Start®, radio TQ 2.4 GHz, transmisión de 2 velocidades y 8 amortiguadores Ultra Shocks.",
    specs: ["Monster truck nitro 4WD", "Arranque eléctrico EZ-Start®", "Transmisión 2 velocidades", "Suspensión de 4\" con 8 amortiguadores"],
  },
  {
    id: "ridgerunner",
    name: "Redcat RidgeRunner 1/10",
    cat: "monster",
    price: 350,
    tag: null,
    img: "assets/img/ridgerunner.webp",
    desc: "Buggy rápido y resistente con tracción 4x4, suspensión de alto recorrido y gran estabilidad off-road.",
    specs: ["Escala 1/10, 4x4", "Suspensión de alto recorrido", "Gran estabilidad", "Listo para correr (RTR)"],
  },
  {
    id: "volcano-epx",
    name: "Redcat Volcano EPX 4WD",
    cat: "monster",
    price: 380,
    tag: null,
    img: "assets/img/volcano-epx.webp",
    desc: "Monster truck eléctrico 4WD con motor brushed 540 y neumáticos de alto agarre para todo terreno.",
    specs: ["Monster truck 4WD", "Motor brushed 540", "Listo para correr (RTR)", "Neumáticos de alto agarre"],
  },
  {
    id: "mt18",
    name: "Redcat MT-18 Monster Truck 1/18",
    cat: "monster",
    price: 225,
    tag: null,
    img: "assets/img/mt18.webp",
    desc: "Monster truck compacto listo para correr, con neumáticos de gran agarre y chasis resistente.",
    specs: ["Escala 1/18, 4WD", "Listo para correr (RTR)", "Chasis resistente", "Azul y rojo disponibles"],
  },
  {
    id: "volcano-16",
    name: "Redcat Volcano 16 1/16",
    cat: "monster",
    price: 190,
    tag: "oferta",
    img: "assets/img/volcano-16.webp",
    desc: "La puerta de entrada al off-road: monster 4WD eléctrico escala 1/16 listo para correr.",
    specs: ["Escala 1/16, 4WD", "Motor brushed", "Listo para correr (RTR)", "Rojo y azul disponibles"],
  },
  {
    id: "excavadora",
    name: "Excavadora Caterpillar RC 1/24",
    cat: "monster",
    price: 200,
    tag: null,
    img: "assets/img/excavadora.webp",
    desc: "Totalmente funcional y fuerte para trabajos de construcción a escala.",
    specs: ["Escala 1/24", "Totalmente funcional", "Brazo articulado", "Construcción a escala"],
  },

  /* ---------- Camiones y Trailers (Tamiya 1:14) ---------- */
  {
    id: "grand-hauler",
    name: "Tamiya Grand Hauler 1/14",
    cat: "camiones",
    price: 700,
    tag: null,
    img: "assets/img/grand-hauler.webp",
    desc: "Tráiler RC de alto detalle: chasis metálico, suspensión de ballestas y cabina personalizable.",
    specs: ["Escala 1/14", "Chasis metálico", "Suspensión de ballestas", "Cabina personalizable"],
  },
  {
    id: "fuel-tank-trailer",
    name: "Tamiya Fuel Tank Trailer 1/14",
    cat: "camiones",
    price: 700,
    tag: null,
    img: "assets/img/fuel-tank-trailer.webp",
    desc: "Remolque cisterna a escala 1:14 con chasis metálico y componentes en aluminio pulido, para complementar la serie de camiones RC Tamiya.",
    specs: ["Escala 1/14", "Chasis metálico", "Aluminio pulido", "Compatible serie Tamiya"],
  },
  {
    id: "tamiya-mfc-tractor",
    name: "Tamiya Tractor Truck — Unidad Multifunción",
    cat: "camiones",
    price: 800,
    tag: null,
    img: "assets/img/tamiya-mfc-tractor.webp",
    desc: "Unidad multifunción Tamiya para camiones RC: control de sonido, vibración, luces y señales para los modelos Tractor Truck a escala 1:14.",
    specs: ["Sonido de motor y claxon", "Luces y señales", "Vibración realista", "Camiones Tamiya 1:14"],
  },
  {
    id: "tamiya-mfc-02",
    name: "Tamiya MFC-02 — Pick-Up Truck",
    cat: "camiones",
    price: 800,
    tag: null,
    img: "assets/img/tamiya-mfc-02.webp",
    desc: "Unidad multifunción MFC-02 para Pick-Up Truck RC: luces, sonidos de motor, claxon, sirena y efectos realistas a escala 1:14.",
    specs: ["Luces y sirena", "Sonidos de motor y claxon", "Efectos realistas", "Escala 1:14"],
  },

  /* ---------- Aviones RC ---------- */
  {
    id: "tiger-moth",
    name: "Tiger Moth 20cc",
    cat: "aviones",
    price: 850,
    tag: null,
    img: "assets/img/tiger-moth.webp",
    desc: "Biplano de alto rendimiento con motor 20 cc y estructura resistente, optimizado para acrobacias, loops y vuelo rápido.",
    specs: ["Motor 20 cc", "Estructura reforzada", "Acrobacias y loops", "Vuelo en exteriores"],
  },
  {
    id: "f4-phantom",
    name: "F-4 Phantom 32 DF Jet",
    cat: "aviones",
    price: 596,
    tag: "top",
    img: "assets/img/f4-phantom.webp",
    desc: "Jet RC con turbina ducted fan, fuselaje aerodinámico y alto rendimiento para vuelo deportivo.",
    specs: ["Jet con ducted fan", "Fuselaje aerodinámico", "Alto rendimiento", "Vuelo deportivo"],
  },
  {
    id: "edge-as3x",
    name: "BNF AS3X Edge S40",
    cat: "aviones",
    price: 500,
    tag: null,
    img: "assets/img/edge-as3x.webp",
    desc: "Acrobático de alto rendimiento con estabilización AS3X, listo para volar con precisión y control avanzado.",
    specs: ["Estabilización AS3X", "Diseño acrobático", "Control avanzado", "Bind-N-Fly (BNF)"],
  },
  {
    id: "t28-trojan",
    name: "T-28 Trojan",
    cat: "aviones",
    price: 490,
    tag: null,
    img: "assets/img/t28-trojan.webp",
    desc: "El clásico entrenador militar de ala baja con tren de aterrizaje retráctil, ideal para maniobras avanzadas.",
    specs: ["Entrenador militar clásico", "Ala baja", "Tren retráctil", "Maniobras avanzadas"],
  },
  {
    id: "ultra-stick",
    name: "Ultra Stick 10cc",
    cat: "aviones",
    price: 475,
    tag: null,
    img: "assets/img/ultra-stick.webp",
    desc: "Ala alta con motor 10 cc, diseñado para vuelo acrobático y rendimiento avanzado en exteriores.",
    specs: ["Motor 10 cc", "Ala alta", "Vuelo acrobático", "Exteriores"],
  },
  {
    id: "convergence-vtol",
    name: "Convergence VTOL FPV",
    cat: "aviones",
    price: 465,
    tag: "nuevo",
    img: "assets/img/convergence-vtol.webp",
    desc: "Híbrido de ala fija y multirrotor: despegue vertical, transición automática y compatibilidad FPV.",
    specs: ["Despegue vertical (VTOL)", "Transición automática", "Compatible FPV", "Ala fija + multirrotor"],
  },
  {
    id: "ranger-v2",
    name: "FMS Ranger V2 RTF",
    cat: "aviones",
    price: 285,
    tag: "nuevo",
    img: "assets/img/ranger-v2.webp",
    desc: "El avión ideal para empezar: estable, resistente y listo para volar, con despegue corto y control suave.",
    specs: ["Listo para volar (RTF)", "Ideal principiantes", "Despegue corto", "Vuelo estable"],
  },
  {
    id: "stryker",
    name: "F27Q Stryker",
    cat: "aviones",
    price: 230,
    tag: null,
    img: "assets/img/stryker.webp",
    desc: "Ala voladora ágil y resistente, ideal para combates simulados y vuelo dinámico de alto rendimiento.",
    specs: ["Ala voladora", "Ágil y resistente", "Vuelo dinámico", "Alto rendimiento"],
  },
  {
    id: "night-vapor",
    name: "UMX Night Vapor",
    cat: "aviones",
    price: 175,
    tag: null,
    img: "assets/img/night-vapor.webp",
    desc: "Ultraligero para vuelo en interiores con capacidades acrobáticas precisas y luces para volar de noche.",
    specs: ["Ultraligero de interior", "Luces para vuelo nocturno", "Acrobacias precisas", "Vuelo lento y controlado"],
  },
  {
    id: "arf-beast-60",
    name: "ARF Beast 60s",
    cat: "aviones",
    price: 600,
    tag: null,
    img: "assets/img/arf-beast-60.webp",
    desc: "Biplano acrobático a escala para motor glow o eléctrico, con estructura ligera de madera y diseño ARF de fácil ensamblaje.",
    specs: ["Biplano acrobático", "Glow o eléctrico", "Estructura de madera", "ARF, casi listo para volar"],
  },
  {
    id: "umx-fpv-vapor",
    name: "E-flite UMX FPV Vapor",
    cat: "aviones",
    price: 770,
    tag: null,
    img: "assets/img/umx-fpv-vapor.webp",
    desc: "Avión ultramicro para vuelo en interiores con sistema FPV, ultraligero y estable para maniobras precisas en espacios reducidos.",
    specs: ["Ultramicro UMX", "Compatible FPV", "Vuelo interior", "Ultraligero y estable"],
  },
  {
    id: "hh-mini-vapor",
    name: "HobbyZone Mini Vapor",
    cat: "aviones",
    price: 145,
    tag: null,
    img: "assets/img/hh-mini-vapor.webp",
    desc: "Avión de 338 mm de envergadura y solo 12,5 g, con motor sin escobillas de 17.000 Kv, ideal para vuelo interior y acrobacias precisas.",
    specs: ["Envergadura 338 mm", "Peso 12,5 g", "Motor brushless 17.000 Kv", "Vuelo interior acrobático"],
  },
  {
    id: "stryker-180",
    name: "E-flite F-27Q Stryker 180",
    cat: "aviones",
    price: 150,
    tag: null,
    img: "assets/img/stryker-180.webp",
    desc: "Ala delta de combate ligera y ágil en maniobras, diseñada para vuelos deportivos y simulaciones tácticas realistas.",
    specs: ["Ala delta de combate", "Ágil y rápido", "Ligero y resistente", "Vuelo deportivo"],
  },

  /* ---------- Helicópteros ---------- */
  {
    id: "blade-150fx",
    name: "Blade 150 FX",
    cat: "helis",
    price: 170,
    tag: "top",
    img: "assets/img/blade-150fx.webp",
    desc: "Helicóptero listo para volar con excelente estabilidad, rotor de paso fijo y fácil manejo.",
    specs: ["Listo para volar (RTF)", "Rotor de paso fijo", "Excelente estabilidad", "Fácil manejo"],
  },
  {
    id: "blade-mcx2",
    name: "Blade MCX2",
    cat: "helis",
    price: 130,
    tag: null,
    img: "assets/img/blade-mcx2.webp",
    desc: "Helicóptero listo para volar, económico y de altas prestaciones. Perfecto para empezar.",
    specs: ["Listo para volar (RTF)", "Ideal principiantes", "Vuelo en interiores", "Económico"],
  },

  /* ---------- Baterías ---------- */
  {
    id: "hexfly-lipo-3s",
    name: "Hexfly LiPo 3S 11.1V 5000mAh 30C",
    cat: "energia",
    price: 145,
    tag: null,
    img: "assets/img/lipo-hexfly-3s.webp",
    desc: "Energía de competencia para exprimir tu RC: 5000mAh de capacidad con descarga 30C constante.",
    specs: ["11.1V, 3S", "5000 mAh", "Descarga 30C", "Máximo rendimiento"],
  },
  {
    id: "eflite-lipo-4s",
    name: "E-flite LiPo 4S 14.8V 2800mAh 30C",
    cat: "energia",
    price: 60,
    tag: null,
    img: "assets/img/lipo-eflite-4s.webp",
    desc: "Batería potente 4S ideal para máximo rendimiento en aviones y helicópteros RC.",
    specs: ["14.8V, 4S", "2800 mAh", "Descarga 30C", "Ideal para vuelo RC"],
  },
  {
    id: "hexfly-nimh-7s",
    name: "Hexfly NiMh 7S 8.4V 3000mAh",
    cat: "energia",
    price: 55,
    tag: null,
    img: "assets/img/nimh-hexfly.webp",
    desc: "Batería NiMh confiable de 3000mAh, ideal para autos RC eléctricos de uso intensivo.",
    specs: ["8.4V, 7S", "3000 mAh", "Química NiMh", "Uso intensivo"],
  },
  {
    id: "powerhobby-lipo-3s",
    name: "Powerhobby LiPo 3S 11.1V 1300mAh 120C",
    cat: "energia",
    price: 35,
    tag: "oferta",
    img: "assets/img/lipo-powerhobby-3s.webp",
    desc: "Descarga brutal de 120C en formato compacto: punch inmediato para tu RC.",
    specs: ["11.1V, 3S", "1300 mAh", "Descarga 120C", "Formato compacto"],
  },

  /* ---------- Nitro y Repuestos ---------- */
  {
    id: "nitro-kit",
    name: "Nitro Kit All-in-One Redcat",
    cat: "nitro",
    price: 45,
    tag: null,
    img: "assets/img/nitro-kit.webp",
    desc: "Kit completo para carros a nitro: 2 llaves, chispero, cargador, bote y destornilladores.",
    specs: ["Kit completo nitro", "Chispero + cargador", "Llaves y destornilladores", "Todo en uno"],
  },
  {
    id: "nitro-merlin",
    name: "Combustible Merlin Nitro 2.5L",
    cat: "nitro",
    price: 44,
    tag: null,
    img: "assets/img/nitro-merlin.webp",
    desc: "Combustible nitro de alta calidad en presentación de 2.5 litros para motores de combustión interna.",
    specs: ["2.5 litros", "Alta calidad", "Para motores nitro", "Rendimiento constante"],
  },
  {
    id: "glow-plug",
    name: "Bujías Racer Edge Glow",
    cat: "nitro",
    price: 15,
    tag: null,
    img: "assets/img/glow-plug.webp",
    desc: "Las mejores bujías para carros con motor de combustión interna (nitro).",
    specs: ["Bujía glow", "Encendido confiable", "Para motores nitro", "Larga duración"],
  },
]);
